version: "3.9"

services:
  api:
    image: killyourguts/api
    container_name: my-api
    build: ./app
    user: "node:node"
    ports:
      - "3300:3300"
      - "3302:3302"
      - "3301:3301"
      - "3303:3303"
      - "3304:3304"
      - "3305:3305"
    volumes:
      - "/usr/project/app"
    networks:
      connectors: # define the network, with static IP
        ipv4_address: 173.12.15.10
  proxy:
    image: killyourguts/proxy
    container_name: my-proxy
    build: ./proxy
    user: "root:root"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      connectors: # define the network, with static IP
        ipv4_address: 173.12.15.20

networks:
  connectors: # build a custom network, to make connection between the containers.
      name: my-connectors
      driver: bridge
      ipam:
        config:
          - subnet: "173.12.15.0/24"
      attachable: true