version: "3.9"

services:
  api:
    image: killyourguts/api
    container_name: my-api
    build: ./app
    user: "node:node"
    ports:
      - "3300:3300"
      - "3302:3302"
      - "3301:3301"
      - "3303:3303"
      - "3304:3304"
      - "3305:3305"
    volumes:
      - "/usr/project/app"
    networks:
      - connector-network
  proxy:
    image: killyourguts/proxy
    container_name: my-proxy
    build: ./proxy
    user: "root:root"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - connector-network
networks:
  connector-network:
      driver: bridge